### ISSUE TITLE
Infinite loop on re.findall

### ISSUE THREAD

**Issue by ncfavier** [mrichar1/clipster#101]
Sometimes clipster goes into 100% CPU usage. I attached gdb to the Python process and found that it was stuck in the call to `re.findall`. I don't know if this is a Python bug or an instance of [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). I have `extract_patterns` disabled so the only potential culprits are the regexes for URIs and emails, `r'\b\S+://\S+\b'` and `r'\b\S+\@\S+\.\S+\b'`. The latter *looks* like it could be problematic because `\S` matches `@` and `.`, but I couldn't find a pathological input.

I'm disabling `extract_uris` and `extract_emails` as a workaround.

**Comment by mrichar1** [comment]
Hi - thanks for putting in the time to do some debugging!

I can well believe this is a backtracking issue - both regexes have the problem that there is a chance for 'mis-matching' - for urls it could be something weird like `http::////http::////.com`

The easy fix is probably to choose better regexes for these.I'll look at patching these today, and then we probably just have to wait and see if the infinite loop resurfaces.

Just going to mention #86 as it may be related...

**Comment by mrichar1** [comment]
That's `clipster` updated with some new regexes - I've tried to find ones which are specific enough but not horrifically complicated that they'll lead to more problems. Now we have to just wait and see if the bug is still reproduceable!

**Comment by ncfavier** [comment]
Oh but I still have extraction disabled, so it means nothing. Guess no one *else* ran into it in the meantime :)
