### ISSUE TITLE
delete items from clipboard history

### ISSUE THREAD

**Issue by mrichar1** [mrichar1/clipster#11]
There should be some way to delete things from the clipboard history (other than opening the history file in a JSON editor...)

2 possible interfaces:
- DEL key/buttons in the UI.
- command-line option - e.g. --delete <pattern>

**Comment by mrichar1** [comment]
Added use of `<del>` key in UI to delete items (multiple-row selection is also now possible).

Adding multi-select means that mouse button doesn't 'activate' the selection - will need to add a 'submit' button or similar to provide continued mouse functionality.

**Comment by bennylb** [comment]
Very useful functionality. Are you deleting items by matching the currently selected item as a string or using an key/index associated with the item selected when pressing `<del>`? I'm just thinking forward to how the `--delete` command line option will work.

**Comment by mrichar1** [comment]
Select button added to allow continued mouse operation: 1007d6679c1c54c52ad2a29ff8377583ec573d13

**Comment by mrichar1** [comment]
My plan is that `--delete` should work with strings or patterns (regexes) - I think it would not get used much if it took positional arguments.

I can see use cases for both exact matches and partial matches though. Partial matches with regex would be great for things like: `--delete \b\S+\/\/.+:.+@` to remove accidentally cached urls with passwords in them.  However I'm not sure if I want to force people to understand regexes to delete exact matches, i.e. `--delete fish` is friendlier than `--delete ^fish$`

Perhaps we need both --delete and --delete-pattern? Or maybe I'm over-thinking this!

**Comment by bennylb** [comment]
I think providing both would add versatility. Maybe with an option `-r` for regex.

**Comment by mrichar1** [comment]
Simple command-line delete functionality added in 8deadbe (though actually use `HEAD` if you want to test this, as the documentation updates etc happened in later commits).

```
  -r [DELETE], --delete [DELETE]
                        Delete from clipboard. Deletes matching text, or if no
                        argument given, deletes last item.
```

So `-r` alone deletes last item, and `-r secret` will delete the clipboard entry `secret`.

I'm going to close this issue for now - if extended delete functionality is really needed we can open a new issue for regex deletes etc.
