### ISSUE TITLE
Create version for clipster

### ISSUE THREAD

**Issue by diogoleal** [mrichar1/clipster#13]
I suggest you create a version for clipster to be packaged.

**Comment by mrichar1** [comment]
This is definitely on the todo list - thanks for putting it here so I don't forget!

At present the 'API' is changing quite a lot, and features and their implementation are coming and going, but once that settles down I plan to make a release. I'll probably also use setup.py or similar to at least give people some help to packaging it up.

**Comment by mrichar1** [comment]
Hi - sorry for the delay on this one!

I've just made an initial release: https://github.com/mrichar1/clipster/releases

It includes a basic setup.py so hopefully any builds can be made off that (please submit new issues/PRs if you have any change requirements for setup.py). Thanks!
