### ISSUE TITLE
Option to sync the two clipboards

### ISSUE THREAD

**Issue by mrichar1** [mrichar1/clipster#14]
It might be useful to have any changes to a clipboard be copied to the other one, for those people who always want to use mouse selection/Ctrl-C/V and not have to work out which board a selection went to.

Points to note:
* copying boards will trigger events which could result in an infinite copy loops. Stop event handling, or be clever with board content comparison to avoid this.
* If this is enabled, if there any need to store separate histories? #12 is already asking for the option to not write one (or both?) boards, which would tie in here.

**Comment by andya9** [comment]
:+1: single history for both should maybe be the default, or maybe even the only one (?)

**Comment by mrichar1** [comment]
This patch enables clipboard synchronisation. Note that only boards listed in `active_selections` will be synchronised.

The history file continues to update both boards, even with synchronisation enabled.  I decided to keep this behaviour, since there are no easy ways to decide what should be in the 'single history' if the user has been running with separate boards, then turns on syncing, or turns it off and reverts to separate boards.
