### ISSUE TITLE
Extension detection fails when copying linewise from vim.

### ISSUE THREAD

**Issue by bduncan** [mrichar1/clipster#18]
When selecting a block in vim using shift-v and using up or down arrows, it copies a new selection for each new added line, so you get multiple very similar clipboard entries.
![o10](https://cloud.githubusercontent.com/assets/216631/13118582/d340bfa0-d59c-11e5-8096-f2803212450e.png)

**Comment by mrichar1** [comment]
The `clipster` answer is probably:

set `smart_update` to a high number to catch this behaviour.

However there may also be a `vim` answer:

On Ubuntu, vim is compiled without clipboard support:

`/usr/bin/vim.basic --version | grep clipboard`

Clipboard support allows yanking etc to the selection or clipboard registers using e.g. `+y`.

Instead, clipboard support is enabled in the 'GUI' packages: `vim-gtk` and `vim-athena` (which replace `/usr/bin/vim` via alternatives)

'vim-gtk' seems to also add the 'shift-v selects directly to the clipboard' behaviour which you're seeing, but 'vim-athena' does not. (instead requiring the `+` or `*` register operators).

if you like the vim-gtk behaviour, but want a neater clipboard, probably the best option is to use `smart-update`

If you don't like it, either replace `vim-gtk` with `vim-athena`, or dig about in the `vim-gtk` source/config to see if the behaviour can be toggled.
