### ISSUE TITLE
Copied text lost when closing

### ISSUE THREAD

**Issue by andya9** [mrichar1/clipster#2]
When I copy e.g. from my editor, then I close it, the selection is not available anymore for other applications (i.e. the system’s clipboard is emptied) unless I open clipster and copy it again from it.

**Comment by mrichar1** [comment]
I thought I'd handled this by looking for clipboard events where they contained empty strings, but hadn't realised that a clipboard can be explicitly cleared too.

I've added some code to handle this - please can you grab the latest version and see if that resolves your issue?

Thanks for reporting this one!

83c81c9d28fb0855f388930ee6f7d788f8054d9e

**Comment by andya9** [comment]
It works perfectly now!
thank’you very much for the fast answer!

**Comment by andya9** [comment]
It seems that after refactoring this isn’t working again (for example with firefox)

**Comment by mrichar1** [comment]
Thanks for spotting this. I'd switched to using the

**Comment by andya9** [comment]
Perfect :sparkles: 
Thanks!
