### ISSUE TITLE
Text selection highlighting vanishes when `sync_selections = yes`

### ISSUE THREAD

**Issue by h0tbird** [mrichar1/clipster#21]
If I set `sync_selections = yes` and I select some text in my `urxvt` terminal, the selection highlight vanishes away. This might be tricky but I wish to keep the selected text highlighted. Thank you!

**TIP:** If I select the same text twice or more, it stays highlighted the second time onwards.

**Comment by mrichar1** [comment]
Hi,

I've just tried this myself using `urxvt` and the text stays selected:

![image](https://cloud.githubusercontent.com/assets/478653/13203953/388603d6-d8bb-11e5-8d74-a61318002a3f.png)

Can you provide any more information on what steps you are taking to select the text, and also add the output of `-lDEBUG` on both client and server?

**Comment by h0tbird** [comment]
Sorry, that was my fault. I was running `xcmenu` alongside `clipster` and both were interfering.
Now that I have stopped `xcmenu` the text stays selected. Thanks for making me realize.
