### ISSUE TITLE
Use `a in b` in smart_update check

### ISSUE THREAD

**Issue by sebastianst** [mrichar1/clipster#31]
I realized that my primary clipboard is often flooded with strings that grow or shrink to the _left_. This is caused, for example, when I select text with the mouse from _right_  to _left_ . Then the `smart_update` feature doesn't work, because in method `update_history`, the checks in line 372 use `str.startswith()`.

Would you maybe agree to switch to `a in b` here to detect growth in any direction? Or would you rather make that optional via the configuration?

(Update: python strings don't have a `contains()` method :) )

**Comment by mrichar1** [comment]
Thanks for spotting this!

I've replaced `startswith` with `in` and skipped the `smart_update` logic if the strings are identical (as the `duplicates` code handles this). Also added some tests:  9cdeeff27e336961a83009474c5375b97576312e

Let me know if this fixes the issue for you - the update_history method could probably do with some refactoring to make it tidier and more pythonic, but it should be working fine.

**Comment by sebastianst** [comment]
Works as expected, thank you!

**Comment by sebastianst** [comment]
Ok there's more ;)

- [ ] It would be nice to set a (optional) different smart-diff for shrinking. I would rather set growing to ~8, but shrinking only to 1 or 2. I can implement that and send a PR.
- [ ] Detect growth by words and lines. Diffs are nice for growth/shrinkage of code or mouse selection, but when I am writing text, I often select by hitting `Ctrl+Shift+ ←...←` (or `→...→`), and then the primary selection grows by words, which are not detected if the diff is shorter than a word. So the logic would be: Smart-update (i.e., pop last) if growing/shrinking by 1 word or line (or even a configurable amount of words/lines, since it wouldn't make a big difference implementation-wise). I can send a PR for that as well. (Open question: What separates words? Spaces or `\s` or `\W` or a custom list of chars?)

Thoughts? I should put that into a new Issue as an enhancement.
