### ISSUE TITLE
OS Error: Too many files open

### ISSUE THREAD

**Issue by JackofSpades707** [mrichar1/clipster#35]
```
❯ Traceback (most recent call last):                                                                                                                                                     [17:41:09]
  File "/usr/bin/clipster", line 484, in owner_change
  File "/usr/bin/clipster", line 416, in update_history
  File "/usr/bin/clipster", line 317, in write_history_file
  File "/usr/lib/python3.6/tempfile.py", line 342, in mkstemp
  File "/usr/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/home/jack/.config/clipster/tmp0tv2av8_'
Traceback (most recent call last):
  File "/usr/bin/clipster", line 484, in owner_change
  File "/usr/bin/clipster", line 416, in update_history
  File "/usr/bin/clipster", line 317, in write_history_file
  File "/usr/lib/python3.6/tempfile.py", line 342, in mkstemp
  File "/usr/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/home/jack/.config/clipster/tmp9iayxe0f'
```

I'd love to post something more meaningful than just a traceback but I cannot seem to pinpoint the cause. (This does repeatedly happen occasionally though)

Config below :

```
[clipster]
data_dir = /home/jack/.config/clipster
default_selection = PRIMARY
active_selections = PRIMARY,SECONDARY,CLIPBOARD
sync_selections = yes
history_file = %(data_dir)s/history
history_size = 5000
history_update_interval = 30
write_on_change = yes
socket_file = %(data_dir)s/clipster_sock
pid_file = %(data_dir)s/clipster.pid
max_input = 50000
row_height = 3
duplicates = no
smart_update = 1
extract_uris = yes
extract_emails = yes
extract_patterns = no
filter_classes = ""
```

**Comment by mrichar1** [comment]
Thanks for reporting this bug!

It looks like we were never closing the history file tempfiles properly - it was only a matter of time until someone ran clipster for long enough to hit it.

I've overhauled the write_history_file() method to do things properly - please let me know if this fixes your issue.

**Comment by JackofSpades707** [comment]
Since the commit I've reinstalled clipster using the Archlinux AUR package here https://aur.archlinux.org/packages/clipster-git (which pulls the src from this repo)

I will post an update within the next couple of days or so. (sometimes it would take a couple days for this issue to occur)

Site note : I do have a VM running via VMWare quite often, and the clipboard is synced between the VM and Host OS

Thank you for the quick reply & quick solution :) It is greatly appreciated

**Comment by JackofSpades707** [comment]
I think that did the trick :)
Thanks again for developing such a useful tool!
