### ISSUE TITLE
newlines get removed sometimes

### ISSUE THREAD

**Issue by magnetophon** [mrichar1/clipster#45]
I'm sorry for not having a clearer idea of when this happens, but sometimes a multi-line copy turns into a one-line paste.

Here's how I use clipster (bound to a key in my WM):
```
clipster -o -n 200 -0 | rofi -i -dmenu -sep '\x00' -eh 2 -p paste: | tr -d '\n' | clipster
```

**Comment by mrichar1** [comment]
I'm guessing it's the `tr -d '\n'` - this strips all new lines from the output. e.g.

```
$ echo -e "cat\n\n\ndog"
cat

dog
$echo -e "cat\n\ndog" |tr -d '\n'
catdog$
```

**Comment by magnetophon** [comment]
Thanks!
The error was on my end, but the solution was on yours!  😃
