### ISSUE TITLE
Move LICENSE.md to /usr/share/license/clipster/ instead of /usr/share/doc/clipster/

### ISSUE THREAD

**Issue by chron-isch** [mrichar1/clipster#49]
Hi, 

could you change
`data_files = [("share/doc/clipster", ["LICENSE.md", "README.md"])],`
in setup.py to
`data_files = [("share/doc/clipster", ["README.md"]), ("share/license/clipster", ["LICENSE.md"])],`
since that's were the license file actually belongs?

Thanks!

**Comment by mrichar1** [comment]
Hi,

It looks like `/usr/share/licenses` path exists on Redhat and Arch systems - but not on Debian systems. I'll tentatively move it there for now, and hopefully it won't be an issue for debian developers if it needs to be put somewhere else during packaging.

**Comment by mrichar1** [comment]
Done in  b0b75aa

**Comment by chron-isch** [comment]
Thanks,

I just wanted to create a proper PKGBUILD for the release version, since the Archlinux AUR only has the git version.

If the Debian guys don't agree, I could also just patch it in the PKGBUILD or not use setup.py.
