### ISSUE TITLE
History isn’t written sometimes

### ISSUE THREAD

**Issue by andya9** [mrichar1/clipster#5]
As the title says, I noticed that history sometimes (most of the times) doesn’t get written (the file isn’t created, or if it exists it isn’t updated). Still, if I launch clipster -s I get everything (until I restart the demon). 
I tried all the -l modes, but it seems nothing strange is happening.

**Comment by mrichar1** [comment]
Hi,

The history file is currently only written on clean exit - which should happen if clipster exits or is killed, but not if it is force killed or dies unexpectedly. Until then the clipboard is held in memory, so -s etc still work. I really should change this to be more reliable!

I'll see about updating clipster to be writing the history file more frequently - I don't necessarily want it writing on every clipboard event (as this will add unnecessary wakeups and writes which could be a bit inefficient) but I'll see if I can find a good idle point/interval to make writes in.

**Comment by andya9** [comment]
I too think it would be too much writing on every event.
One last thing: I don’t understand how to make it exit cleanly. If I start the demon in my .xinitrc (clipster -d &), then I restart my wm (openbox) or reboot I can’t find the history file

**Comment by mrichar1** [comment]
I've added some new code to make history file writing a bit more flexible... 9dfca149a1d711eaffe6e2d11b8c875a69075d0f

2 new config options:

`history_update_interval = X (seconds)` - history will be flushed to file every X seconds, if the in-memory history has changed.

`write_on_change = yes|no` - history will be flushed to file immediately after the clipboard changes.

The default behaviour is now to write out every 60 seconds (if changed), as a good half-way between reliability and resource hungriness. If you want to more certain of backing up your history, either reduce the interval, or enable write_on_change for immediate writes.

Note, in all cases the history file will only come into being once clipster has recorded clipboard changes, and equally the file won't be touched if you start and stop clipster without changing the clipboard contents.

Let me know if this a) fixes your issue and b) offers a suitable amount of flexibility for you.

**Comment by mrichar1** [comment]
clipster should shut down cleanly in response to 'nice' signals, like SIGINT and SIGTERM. It will dump core, or just die in response to SIGQUIT, SIGABRT and SIGKILL.

I would imagine that shutting down a window manager/X should cause one of the nice signals to be sent to clipster - however there's a chance that it's doing something a bit 'harder'.  You could try seeing if you get any useful output from clipster by updating your .xinitrc to be:

    clipster -d -l DEBUG >/tmp/clipster.log &

Then restarting your wm and seeing if the log file has `DEBUG:Daemon exiting...` followed by one of `DEBUG:Writing history to file.` or `DEBUG:History unchanged - not writing to file.`

**Comment by andya9** [comment]
This is perfect! 
I really appreciate your help :smile:
