### ISSUE TITLE
clipster fails to delete entries containing unicode characters

### ISSUE THREAD

**Issue by demure** [mrichar1/clipster#50]
In testing, I have found that clipster errors and fails to delete any entry containing unicode.

> ~ -> clipster -d -l DEBUG
DEBUG:Debugging Enabled.
DEBUG:Merged config: [('active_selections', 'PRIMARY,CLIPBOARD'), ('data_dir', '/home/demure/.local/share/clipster'), ('default_selection', 'PRIMARY'), ('duplicates', 'no'), ('extract_emails', 'yes'), ('extract_patterns', 'no'), ('extract_uris', 'yes'), ('filter_classes', ''), ('history_file', '/home/demure/.local/share/clipster/history'), ('history_size', '200'), ('history_update_interval', '60'), ('max_input', '50000'), ('pid_file', '/home/demure/.local/share/clipster/clipster.pid'), ('row_height', '3'), ('smart_update', '1'), ('socket_file', '/home/demure/.local/share/clipster/clipster_sock'), ('sync_selections', 'no'), ('write_on_change', 'no')]
DEBUG:Writing history file every 60 seconds
DEBUG:Client connection received.
DEBUG:Received: sig:SELECT, board:CLIPBOARD, count:0
>
>(clipster:1402): Gtk-WARNING **: Allocating size to GtkDialog 0x56208489e330 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
DEBUG:Deleting history entry: ☃
>/usr/local/sbin/clipster:217: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if self.read_board(board) == item:
>/usr/local/sbin/clipster:349: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if text in self.boards[board]:
>DEBUG:Deleting history entry:   ☈
>DEBUG:Client connection received.
>DEBUG:Received: sig:SELECT, board:CLIPBOARD, count:0
>
>(clipster:1402): Gtk-WARNING **: Allocating size to GtkDialog 0x5620849d4560 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
>DEBUG:Deleting history entry: ☃
>DEBUG:Deleting history entry:   ☈
>DEBUG:Client connection received.
>DEBUG:Received: sig:SELECT, board:CLIPBOARD, count:0
>
>(clipster:1402): Gtk-WARNING **: Allocating size to GtkDialog 0x562084a32e50 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
>DEBUG:Deleting history entry: ☃
>DEBUG:Deleting history entry:   ☈

Thank you for your time.
-demure

**Comment by mrichar1** [comment]
Hi,

Thanks for this report. I'm trying to test this myself, but can't seem to reproduce the problem using the latest commit form `master` branch:

client:
```
^$ echo -n "в" python3 ./clipster
```
server:
```
^$ python3 ./clipster -d -lDEBUG
DEBUG:Client connection received.
DEBUG:Received: sig:BOARD, board:PRIMARY, count:0
DEBUG:Received content: в
DEBUG:owner-change event!
DEBUG:selection: PRIMARY
DEBUG:Selection in 'active_selections'
DEBUG:Selection is text.
DEBUG:Updating clipboard: PRIMARY
DEBUG:Writing history to file.
DEBUG:['в']
```

client:
```
^$ python3 ./clipster -r в
```

server:

```
DEBUG:Client connection received.
DEBUG:Received: sig:DELETE, board:PRIMARY, count:0
DEBUG:Deleting clipboard items matching text: в
DEBUG:Removing from history.
DEBUG:owner-change event!
DEBUG:selection: PRIMARY
DEBUG:Selection in 'active_selections'
DEBUG:Selection is not text - ignoring.
DEBUG:Writing history to file.
DEBUG:[]
```

Same behaviour whether deletion occurs form command-line or GUI, and regardless of position of unicode string in the history.

Can you confirm which version of clipster and python you are using?  Thanks!

**Comment by demure** [comment]
Thanks for looking into this.
I am on debian sid, and am running from the most recent git version when I reported this.

Something I noticed in your test is that you are doing it all from the cli. I've been using the pop up `clipster -sc`. While recreating your tests, I notice you don't double check the contents of your clipboard history (or at least you didn't post them). After cleanly starting the daemon, and deleting the unicode entry from the command line, I get same output as you.... *but* the entry is still there if I do a fresh `clipster -sc`.

**Comment by mrichar1** [comment]
I just re-read your logging output, and noticed the `UnicodeWarning` which somehow I'd missed before.

Turns out I wasn't correctly decoding the input selected from the UI, and then wasn't seeing this bug because it only hits on python2 (while I was testing with python3).

Have now added a `safe_decode()` in the appropriate place, and it seems to work for me on python2 and python3. As such have pushed a new commit, tagged 1.0.3.

Please try this and let me know if this fixes your problem!

**Comment by demure** [comment]
That seems to have done the trick, thank you!
