### ISSUE TITLE
GUI lacks WM attributes

### ISSUE THREAD

**Issue by mrichar1** [mrichar1/clipster#58]
Currently the GUI window doesn't have any WM_* attributes set - like NAME or CLASS so xprop shows (on i3):

```
WM_NAME(STRING) = "[i3 con] floatingcon around 0x55fa99de0030"
WM_CLASS(STRING) = "i3-frame", "i3-frame"
```

This may cause unexpeted issues, especially in cases where people are using these attributes to assign the GUI to workspaces etc.

WM attributes should be added - at least NAME and CLASS but possibly also things like roles, and maybe popup-esque attributes.

**Comment by mrichar1** [comment]
Turns out Gtk automatically sets WM_NAME and CLASS appropriately - I was mis-using `xprop`.

**Comment by oldgaro** [comment]
Oh I can add that if one assign st terminal to a specific workspace both Clipster and Steam will obey that assignment...just too weird....

shared libraries?

**Comment by mrichar1** [comment]
Thanks for that report - can you post your i3 config that does the workspace assignment so I can check if I can replicate the issue?

**Comment by oldgaro** [comment]
Yes.

assign [class="(?i)st"] → $WS2

https://github.com/oldgaro/dotfiles/blob/master/Distros/i3/config

**Comment by mrichar1** [comment]
i3's `assign` is a regular expression - so this matches all apps that have 'st' anywhere in the name :smile: 

If you want just `st`, I think you need `(?i)^st$`

**Comment by oldgaro** [comment]
facepalm........haha
