### ISSUE TITLE
Deleting items doesn't seem to work properly

### ISSUE THREAD

**Issue by gilbertw1** [mrichar1/clipster#63]
It looks like clipster isn't properly deleting entries. For example if I were to create a clip:

    echo '1234' | clipster -c

And then tried to delete that clip using the following commands:

    echo '1234' | clipster -r
    clipster -r '1234'
    clipster -r

None of them seem to actually result in deleting the item from the clipboard.

By the way I absolutely love this clipboard daemon!

**Comment by mrichar1** [comment]
Hi,

Thanks for reporting this.

I've done some quick testing and can't seem to replicate this - both a plain `-r` and `-r 1234`` seem to work as expected.

One thing catches my eye though - can I just check - are you using `-c` when adding *and* deleting?  If not, the default is to operate on the `PRIMARY`, not the `CLIPBOARD` buffer, so you'll be adding to `CLIPBOARD` but trying to delete from `PRIMARY`.

**Comment by gilbertw1** [comment]
Ah, that's precisely my problem. Adding `--clipboard` to the remove command makes it function exactly as I expect.

Thanks for the quick response!
