### ISSUE TITLE
daemon uses 100% cpu for a while

### ISSUE THREAD

**Issue by magnetophon** [mrichar1/clipster#74]
It started doing so for unknow reaons and stopped by itself about a minute later.
The last entry in the clipboard is from yesterday.
clipster 1.5 with python 3.6

**Comment by mrichar1** [comment]
I've overhauled the gtk selection code using new methods in gtk >3.20 - as highlighted in #66. No guarantees, but I have a gut feeling that the issues with 'over-selection' in certain apps this might be what has caused the cpu issues as well.

If you can replicate this problem using the dev version in that branch, I'd be very grateful to hear back!

**Comment by mrichar1** [comment]
This update is now released as 2.0.0 (498057271e0b4b78cd23c1572490cd85675aa566) - going to close this issue - please let us know if the problem reoccurs!

**Comment by Radivarig** [comment]
Occasionally I get this and have to kill the process. Not sure how to reproduce
