### ISSUE TITLE
filter_classes does not make any difference

### ISSUE THREAD

**Issue by hringriin** [mrichar1/clipster#75]
I have set `filter_classes = Keepassx2` in my config file but I noticed it is not ignored anymore.

`xprop | grep CLASS` returns `WM_CLASS(STRING) = "keepassx2", "Keepassx2"`

I remember that this setting worked when I set it up in November. I cannot tell since when it is not working anymore.

Any suggestions?

**Comment by mrichar1** [comment]
Sorry for the delay in replying!

This config option was updated in the 1.5.0 release and split into `whitelist_classes` and `blacklist_classes` (in PR #68). As a result you can now both 'filter out' and 'filter in' by class.

If you change your config to: `blacklist_classes = Keepassx2` it should work as expected again.

**Comment by hringriin** [comment]
Very nice, thank you for your reply! :)
