### ISSUE TITLE
suggestion: add ability to 'pin' clipboard entries, so they are readliy available to switch to

### ISSUE THREAD

**Issue by assaf758** [mrichar1/clipster#76]
similar to 'static' attribute of clipit

**Comment by mrichar1** [comment]
Hi - sorry for the delay.

This seems like a nice idea - though I'm not sure how this would be implemented. At the moment the clipster history is a list which is simply appended to/removed from - as such there is no obvious way to 'pin' an item to a particular 'position' in the list.

I'm imagining something like a 'favourites' list, to one side of the main history, which could be accessed by cmd-line flags/hotkeys in the GUI, where position was maintained. But there may be better ways.

I've flagged this as 'help wanted' as I'm a bit busy just now and don't have much time to devote to enhancements, but if someone else wants to do the planning and/or implementing I'm happy to review this as a new feature!

**Comment by dicktyr** [comment]
[snippets](https://en.wikipedia.org/wiki/Snippet_(programming)) are useful but I think they belong in a separate tool

**Comment by mat-m** [comment]
My vote on this one.
Suggestions: 
- (As you said) Add a new board `PERMANENT`
- `ACTION:BOARD:COUNT[:CONTENT]` would be `SEND:PERMANENT:X:CONTENT:` where X is the position in the list
  - Do we accept empty items to allow for ordering ?
  - If we do not, if X is already filled, do we overwrite or do we insert ? Insert is more comfortable, but I don't know if it's easy to implement. 
- A command that takes an item from a board and push it in X position in the PERMANENT board
