### ISSUE TITLE
Clipster crashes when deleting multiple entries quickly from selection window

### ISSUE THREAD

**Issue by electric-ladyland** [mrichar1/clipster#82]
If I have a lot (maybe couple hundred) of entries in my clipboard, I bring up the selection window, and hold down Delete to clear them all out, clipster sometimes crashes completely. It's intermittent. Seems it crashes on delete in quick succession.
Not sure what debugging info I can produce to help... Let me know. My clipster config is [here](https://github.com/electric-ladyland/.dotfiles/blob/master/clipster/clipster.ini).

**Comment by mrichar1** [comment]
Hi, thanks for reporting this!

I've tried some initial tests, adding 100k unique items to the clipboard, then deleting them all by holding Delete through the UI, and can't get clipster to crash after several attempts.

Can you run the clipster daemon in debug mode (clipster -d -lDEBUG) and see if there are any interesting logs when it crashes in this way? Equally, can you see if there are any system errors in syslog etc from e.g. oom_killer in case this is a resource hogging issue?

Of course a workaround to this is to run `clipster --erase-entire-board` from the command-line, but if this is a bug I'd like to get it fixed.

This is sort of linked to #72 (and #36) so mentioning it here to link them.

**Comment by electric-ladyland** [comment]
Thanks for your reply, I will try that and reopen if I can find something concrete to fix.
