### ISSUE TITLE
Packaging up a 2.0.2 release

### ISSUE THREAD

**Issue by jtmoulia** [mrichar1/clipster#84]
Running clipster 2.0.1 from arch's AUR I get a lot of Python deprecation warnings. These are resolved by running the latest from `master`

I can install clipster-git from the AUR, but I'd rather be a step behind the bleeding edge.

Love the package -- thanks!

**Comment by mrichar1** [comment]
Ah, thanks for the nudge - `2.0.2` now released! (Not sure who/what builds new AUR packages, but hopefully it it's automatic!)

**Comment by jtmoulia** [comment]
awesome -- thanks for the quick update @mrichar1 !

**Comment by chron-isch** [comment]
> Ah, thanks for the nudge - `2.0.2` now released! (Not sure who/what builds new AUR packages, but hopefully it it's automatic!)
No it's not automated, in case of clipster it's just me.
For the future it would be way more useful and faster to flag the package 'Out-of-Date' on AUR, I get a notification that way. :)
