### ISSUE TITLE
Ignore clipboard changes from certain apps

### ISSUE THREAD

**Issue by mrichar1** [mrichar1/clipster#9]
Investigate ignoring clipboard changes for certain apps, such as password managers, so as to not cache passwords in history.

In theory, we can look at the clipboard owner, get the WM_NAME, WM_CLASS etc and use a user-defined filter to exclude these... however gtk doesn't seem keen to give us this information.

We can get the owning GDK window associated with the event as follows:

```python
owner = event.owner
```

This window has no useful methods to directly get the X properties though - we have to go via something indirect like libwnck's `window_get` from the xid: https://developer.gnome.org/libwnck/stable/WnckWindow.html#wnck-window-get

```python
xid = owner.get_xid()
wnck_win = Wnck.Window.get(xid)
wm_name = wnck_win.get_name()
wm_class = wnck_win.get_name()
```

However the xid here is NOT the xid of the 'application root' window, and so Wnck returns `None`. Perhaps we need to get it's parent:

```python
parent_xid = owner.get_parent().get_xid()
# Repeat as above...
```

However `get_parent` doesn't ask X for the parent, so seems to always return the root window: https://developer.gnome.org/gdk3/3.16/gdk3-Windows.html#gdk-window-get-parent

This is where I'm stuck for now - if anyone has any ideas I'm interested! I'd rather avoid having to add xlib if I can help it...

**Comment by andya9** [comment]
I don’t think it’s possible without asking the graphic server itself... but using xlib would mean no wayland.
What do other clipboards do? If no one does it, maybe it’s really impossible

**Comment by mrichar1** [comment]
OK - so there are 2 ways to do this - the first doesn't work, the second isn't ideal:

The first way, as suggested before is to use `python-xlib`. However not all windows have properties, so you have to recurse up the window tree to find a parent with properties. However some apps seem to like to use 'un-parented' windows so you never get to a parent with a `WM_CLASS` property before you reach the root window :-(

The second is to look and see what window is active at the point the owner-change event occurs. This is easy to do, but feels very wrong.  However, this is actually what `klipper` does when you use their `Disable Actions for windows of type WM_CLASS` option, so it's got some support out there.

It's very easy to break this by doing: `sleep 10; echo "cat" | clipster` and then changing window focus - however I suspect for the cases where this matters (like `keepass2`) you're unlikely to have any such delay.

I'll see about implementing this second option and let you know when it's ready to test.

**Comment by andya9** [comment]
Good! i didn’t know klipper could do it. 
Sadly it’s too much advanced for me to help with the coding, i’m just a beginner, but i’ll be glad to at least help testing it.

**Comment by mrichar1** [comment]
That should be the changes added - to test, add:

```
filter_classes = KeePass2
```

To your config and if you run `clipster -d -lDEBUG` you should hopefully see:

```
DEBUG:Filter classes enabled for: ['KeePass2']
DEBUG:Active window class is KeePass2
DEBUG:Ignoring active window.
```

In the output when you cut/copy in keepass2 (but no change in behaviour for other apps).

**Comment by andya9** [comment]
i get:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arch/.shortcuts/clipster", line 10, in <module>
    from gi.repository import Gtk, Gdk, GLib, GObject, Wnck
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 100, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Wnck, introspection typelib not found
```

**Comment by andya9** [comment]
i get:
```
Traceback (most recent call last):
  File "/home/arch/.shortcuts/clipster", line 10, in <module>
    from gi.repository import Gtk, Gdk, GLib, GObject, Wnck
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 114, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.5/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.5/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded
```

**Comment by mrichar1** [comment]
I think the issue is that you're missing libwnck 3.0 library, and/or the bindings for it in gi.repository.

Not 100%, but a quick google suggests that this can be found in the following packages for different OSes:

* debian/ubuntu: `libwnck-3-0` and `gir1.2-wnck-3.0`
* arch: `libwnck3` 
* redhat/fedora: `libwnck3-devel`

Let me know if installing that fixes the problem. It might also be necessary to put in another `require_version` line at the top of the file to force the use of the 3.0

**Comment by andya9** [comment]
It’s perfect now; I tried it with firefox and works without flaws. About the wnck, the require_version is needed indeed. I too thought about some missing dependency, but I installed python2-wnck instead of libwnck3, so it didn’t work

**Comment by mrichar1** [comment]
Have added the require_version - thanks for your issue request and testing! :+1:

**Comment by andya9** [comment]
thanks to you for dealing with it!
