### ISSUE TITLE
Gtk-WARNING: Theme parsing error

### ISSUE THREAD

**Issue by kuntau** [mrichar1/clipster#96]
```shell
(clipster:494068): Gtk-WARNING **: 01:47:27.983: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(clipster:494068): Gtk-WARNING **: 01:47:27.983: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(clipster:494068): Gtk-WARNING **: 01:47:27.983: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```

I'm using `clipster` with `roficlip`, whenever I enter the command, I got this warning. Functionality wise, everything worked but it's annoying to see this every time and litter my tui.

https://asciinema.org/a/wb05BwOgAdadbib0QYWrMmSPk

**Comment by mrichar1** [comment]
Theme parsing is down to the local theme config you have, and not a feature of clipster (which is theme agnostic).

Have a look at your local gtk config to see what theming you have set up. Most likely it is an issue in `gtk.css` in the theme you are using (`/usr/share/themes/`) or a mis-config in your config files (e.g. `~/.gtkrc-2.0`).
