### ISSUE TITLE
Question: Any plans on python3 ?

### ISSUE THREAD

**Issue by elundmark** [mrichar1/clipster#97]
Doesn't python2 _die_ next year?

**Comment by mrichar1** [comment]
`clipster` has supported both python2 and 3 from the start - these days I'm only testing against 3 and only developing using 3.

I'll be reviewing the code and docs at the start of next year when 2 officially goes away. There is probably no need to make it stop working on 2, but the docs should reflect that 2 isn't formally supported any more.
