### ISSUE TITLE
[Errno 2] No such file or directory: '/run/user/0/clipster.pid'

### ISSUE THREAD

**Issue by Eleno4kaLap** [mrichar1/clipster#98]
Hello! I try run clipster -d in docker container and get 
`  File "/usr/local/bin/clipster", line 646, in prepare_files
    with open(self.pid_file, 'w') as runf_w:
IOError: [Errno 2] No such file or directory: '/run/user/0/clipster.pid'`

Please tell me how you can solve this problem?

**Comment by mrichar1** [comment]
Docker creates it's PID file in /run/user/{uid}/clipster.pid by default.  Yuo can modify the path of this file by setting `pid_file` to a different filename in the clipster config file. See https://github.com/mrichar1/clipster#config-file for more details.
